# Generated by Django 5.1.11 on 2025-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_chatsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsetting',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
